# -*- coding: utf-8 -*-
"""Yukti.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M1KHBBBbZkfPZOMiGme_XED3l5AwuMLj
"""

name = "yukti"
print(name)

a = 39
b = 78
sum = a+b
print(sum)

n = int(input("enter a number:-"))
i = 1
while i <= 10:
  print(i*n)
  i += 1

# this the pythen program i need to submit it  by deadline of 13 nevember